services:
  web-messenger-backend:
    container_name: web-messenger-backend
    image: kek/web-messenger-backend:latest
    build: ./backend
    ports:
      - 9000:8000
    restart: unless-stopped
    networks:
      - app


  web-messenger-frontend:
    depends_on:
      - web-messenger-backend
    container_name: web-messenger-frontend
    image: kek/web-messenger-frontend:latest
    build: ./frontend
    ports:
      - 8000:3000
    networks:
      - app
    restart: unless-stopped
    environment:
      - REACT_APP_API_HOST=web-messenger-backend # Changed to container name
      - REACT_APP_API_PORT=9000
      - WDS_SOCKET_PORT=0

networks:
  app:
    driver: bridge

